spring:
  application:
    name: eureka-config
  profiles:
    active: native

eureka:
  instance:
    hostname: localhost
    nonSecurePort: 8888
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
