spring:
  application:
    name: eureka-client
  cloud:
    config:
      enabled: true
      discovery:
        enabled: true
        serviceId: eureka-config

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

server:
  port: 2222
