spring:
  application:
    name: employee-service
  cloud:
    config:
      enabled: true
      discovery:
        enabled: true
        serviceId: eureka-config
      
eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: host-one
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
    healthcheck: 
      enabled: true

server:
  port: 9999
